version: "3.7"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-radium
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-radium
    volumes:
      - /dev/shm:/dev/shm
      - ./inputs:/tmp/inputs
    depends_on:
      - selenium-hub
    environment:
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox:3.141.59-radium
    volumes:
      - /dev/shm:/dev/shm
      - ./inputs:/tmp/inputs
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  estuary-viewer:
    image: estuary-viewer:latest
    container_name: estuary-viewer
#    ports:
#      - "8080:8080"
